### ISSUE TITLE
macos安装poword需要依赖pywin32，但是pywin32不支持MacOS

### ISSUE THREAD

**Issue by WangXusheng1225** [CoderWanFeng/poword#1]
macos安装poword需要依赖pywin32，但是pywin32不支持MacOS，导致poword安装失败

**Comment by CoderWanFeng** [comment]
目前无解



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月21日(周二) 中午1:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [CoderWanFeng/poword] macos安装poword需要依赖pywin32，但是pywin32不支持MacOS (Issue #1)




 
macos安装poword需要依赖pywin32，但是pywin32不支持MacOS，导致poword安装失败
